[package]
name = "factorio_mod_notifier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.12"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
poise = "0.6.1"
env_logger = "0.11.2"
sqlx = { version = "0.7", features = [ "runtime-tokio", "tls-rustls", "sqlite" ] }
chrono = "0.4.38"
log = "0.4.21"
dotenv = "0.15.0"
rust-fuzzy-search = "0.1.1"
